%%{init: {
    %% 'theme': 'neo'
}}%%

sequenceDiagram
    %% autonumber
    participant F as Agent / Frida (JS)
    box rgba(248, 255, 237, 1) Emulation
    participant E as Eden Puni (C++)
    participant G as Game
    end
    participant OS as OS / CPU

    Note over F, OS: Hook Installation Phase

    F->>E: NceInstallExternalHook(addr)
    activate E
    E->>G: Read original instruction
    
    alt is PC-Relative?
        E->>E: Mark for Interpretation
    else is Relocatable
        E->>E: Allocate Trampoline
        E->>E: Write Original Inst + Branch
    end

    E->>G: Write UDF #0 (SIGILL)
    E-->>F: Success
    deactivate E

    Note over F, OS: Hook Execution Phase

    activate G
    G->>G: Execute Original Instructions
    G->>OS: Execute UDF #0
    deactivate G
    activate OS
    OS->>E: Signal SIGILL
    deactivate OS
    
    activate E
    
    E->>E: HandleGuestIllegalInstruction()
    
    break SIGILL not caused by hook
        E->>OS: Forward SIGILL (Crash)
         deactivate E
    end
    activate  E

    E->>E: Lookup Hook Callback
    
    E->>F: NceTrampoline(PC, Context)
    deactivate E
    activate F
    F->>F: JS Handler (Interceptor)
    F-->>E: Return
    activate E
    deactivate F
    
    Note over F, OS: Resumption Phase
    
    alt Trampoline Available
        E-->>G: Resume at Trampoline (Native)
    else Interpretation Required
        E-->>E: MatchAndExecuteOneInstruction()
        E-->>G: Resume at Next Instruction
        deactivate E
    end
    
    activate G
    G->>G: Continue Execution
    deactivate G