%%{init: {
    %% 'theme': 'neo'
}}%%

sequenceDiagram
    %% autonumber
    participant F as Agent / Frida (JS)
    box rgb(249, 255, 240) Emulation
    participant E as Eden Puni (C++)
    participant G as Game
    end
    participant OS as OS / CPU

    Note over F, OS: Hook Installation Phase

    activate F
    F->>E: NceInstallExternalHook(addr)
    deactivate F
    activate E
    E->>G: Read original instruction
    
    alt is PC-Relative?
        E->>E: Mark for Interpretation
    else is Relocatable
        E->>E: Allocate Trampoline
        E->>E: Write Original Inst + Branch
    end

    E->>G: Write UDF (SIGILL)
    E-->>F: Success
    activate F
    F->>E: Hook NceTrampoline()
    deactivate F

    Note over F, OS: Hook Execution Phase
    deactivate E

    activate G
    G->>G: Execute Original Instructions
    G->>OS: Execute UDF
    deactivate G
    activate OS
    OS->>E: Signal SIGILL
    deactivate OS
    
    activate E
    
    E->>E: HandleGuestIllegalInstruction()
    
    rect rgba(255, 240, 240, 1)
    break SIGILL not caused by hook
        E->>OS: Forward SIGILL (Crash)
        deactivate E
    end
    end
    activate  E

    E->>E: Lookup Hook Callback
    
    E->>F: Call NceTrampoline()
    deactivate E
    activate F
    F->>F: Interceptor Handler
    F-->>E: Return
    activate E
    deactivate F
    
    Note over F, OS: Resumption Phase
    
    alt Trampoline Available
        E-->>G: Resume at Trampoline (Native)
    else Interpretation Required
        E-->>E: MatchAndExecuteOneInstruction()
        E-->>G: Resume at Next Instruction
        deactivate E
    end
    
    activate G
    G->>G: Continue Execution
    deactivate G